In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('C:\\Users\\Shubham\\Downloads\\Bengaluru_House_Data.csv')
df

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK      NaN       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK      NaN       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK      NaN       3600   5.0      NaN  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK      NaN        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [3]:
df.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [4]:
df.shape

(13320, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   area_type     13320 non-null  object 
 1   availability  13320 non-null  object 
 2   location      13319 non-null  object 
 3   size          13304 non-null  object 
 4   society       7818 non-null   object 
 5   total_sqft    13320 non-null  object 
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB


In [6]:
for column in df.columns:
    print(df[column].value_counts())
    print('*'*20)

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64
********************
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...  
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: availability, Length: 81, dtype: int64
********************
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64
********************
2 BHK         5199
3 BHK        

In [7]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [8]:
df.drop(columns = ['availability','area_type','society','balcony'],inplace = True)

In [9]:
df.describe()

bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    13319 non-null  object 
 1   size        13304 non-null  object 
 2   total_sqft  13320 non-null  object 
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB


In [11]:
df['location'].value_counts()

Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [12]:
df['location'] = df['location'].fillna('Sarjapur Road')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    13320 non-null  object 
 1   size        13304 non-null  object 
 2   total_sqft  13320 non-null  object 
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB


In [14]:
df['size'].value_counts()

2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64

In [15]:
df['size'] = df['size'].fillna('2 BHK')

In [16]:
df['bath'] = df['bath'].fillna(df['bath'].median())

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    13320 non-null  object 
 1   size        13320 non-null  object 
 2   total_sqft  13320 non-null  object 
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB


In [18]:
df['bhk'] = df['size'].str.split().str.get(0).astype(int)

In [19]:
df[df.bhk>20]

location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [20]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [21]:
def convertrange(x):
    temp = x.split('-')
    if len(temp)==2:
        return(float(temp[0]) + float(temp[1])/2)
    try:
        return(float(x))
    except:
        
        return None

In [22]:
df['total_sqft'] = df['total_sqft'].apply(convertrange)

In [23]:
df.head()

location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [24]:
df['price_per_sqft'] = df['price']*100000/df['total_sqft']
df['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...     
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [25]:
df.describe()

total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1572.225941      2.688814    112.565627      2.802778    7.883254e+03
std     1254.823072      1.338754    148.971674      1.294496    1.064303e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.227642e+03
50%     1280.000000      2.000000     72.000000      3.000000    5.416667e+03
75%     1690.000000      3.000000    120.000000      3.000000    7.293505e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [26]:
df['location'] = df['location'].apply(lambda x: x.strip())
location_counts = df['location'].value_counts()
location_counts

Whitefield                            541
Sarjapur  Road                        399
Electronic City                       304
Kanakpura Road                        273
Thanisandra                           237
                                     ... 
1Channasandra                           1
Hosahalli                               1
Vijayabank bank layout                  1
near Ramanashree California resort      1
Abshot Layout                           1
Name: location, Length: 1295, dtype: int64

In [27]:
location_count_less_10 = location_counts[location_counts<=10]
location_count_less_10

BTM 1st Stage                         10
Nagadevanahalli                       10
Basapura                              10
Sector 1 HSR Layout                   10
Dairy Circle                          10
                                      ..
1Channasandra                          1
Hosahalli                              1
Vijayabank bank layout                 1
near Ramanashree California resort     1
Abshot Layout                          1
Name: location, Length: 1054, dtype: int64

In [28]:
df['location'] = df['location'].apply(lambda x:'other' if x in location_count_less_10 else x)

In [29]:
df['location'].value_counts()

other                 2886
Whitefield             541
Sarjapur  Road         399
Electronic City        304
Kanakpura Road         273
                      ... 
Nehru Nagar             11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: location, Length: 242, dtype: int64

#  outliers

In [30]:
df.describe()

total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1572.225941      2.688814    112.565627      2.802778    7.883254e+03
std     1254.823072      1.338754    148.971674      1.294496    1.064303e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.227642e+03
50%     1280.000000      2.000000     72.000000      3.000000    5.416667e+03
75%     1690.000000      3.000000    120.000000      3.000000    7.293505e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [31]:
(df['total_sqft']/df['bhk']).describe()

count    13274.000000
mean       579.732987
std        392.247238
min          0.250000
25%        475.000000
50%        554.000000
75%        627.500000
max      26136.000000
dtype: float64

In [32]:
df.shape

(13320, 7)

In [33]:
df.price_per_sqft.describe()

count    1.327400e+04
mean     7.883254e+03
std      1.064303e+05
min      2.678298e+02
25%      4.227642e+03
50%      5.416667e+03
75%      7.293505e+03
max      1.200000e+07
Name: price_per_sqft, dtype: float64

In [34]:
lower_limit = df['total_sqft'].quantile(0.10)
upper_limit = df['total_sqft'].quantile(0.90)
a = []
for x1 in df['total_sqft']:
    if x1 < lower_limit:
        x1 = lower_limit
        a.append(x1)
    elif x1 > upper_limit:
        x1 = upper_limit
        a.append(x1)
    else:
        a.append(x1)
        
print(a)
df['total_sqft'] = a

[1056.0, 2427.800000000003, 1440.0, 1521.0, 1200.0, 1170.0, 2427.800000000003, 2427.800000000003, 1310.0, 1020.0, 1800.0, 2427.800000000003, 1000.0, 1100.0, 2250.0, 1175.0, 1180.0, 1540.0, 2427.800000000003, 1100.0, 900.0, 1755.0, 2427.800000000003, 1767.0, 900.0, 1250.0, 900.0, 1610.0, 1151.0, 1025.0, 2427.800000000003, 1075.0, 1760.0, 1693.0, 1925.0, 900.0, 1070.0, 1724.0, 1290.0, 1143.0, 1296.0, 1254.0, 900.0, 900.0, 1330.74, 900.0, 970.0, 1459.0, 900.0, 900.0, 1270.0, 1670.0, 2010.0, 1185.0, 1600.0, 1200.0, 2427.800000000003, 1500.0, 1407.0, 900.0, 2427.800000000003, 900.0, 2427.800000000003, 1160.0, 2427.800000000003, 1100.0, 1140.0, 1220.0, 1350.0, 1005.0, 900.0, 1358.0, 1569.0, 1240.0, 2089.0, 1206.0, 1150.0, 2427.800000000003, 900.0, 2427.800000000003, 1660.0, 2427.800000000003, 1326.0, 1325.0, 1499.0, 2427.800000000003, 1665.0, 900.0, 1060.0, 900.0, 1000.0, 1000.0, 1450.0, 1200.0, 1296.0, 1540.0, 2427.800000000003, 1330.0, 1200.0, 1200.0, 2427.800000000003, 900.0, 2400.0, 1007

In [35]:
df.describe()

total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1445.847098      2.688814    112.565627      2.802778    7.883254e+03
std      474.177564      1.338754    148.971674      1.294496    1.064303e+05
min      900.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.227642e+03
50%     1280.000000      2.000000     72.000000      3.000000    5.416667e+03
75%     1690.000000      3.000000    120.000000      3.000000    7.293505e+03
max     2427.800000     40.000000   3600.000000     43.000000    1.200000e+07

In [36]:
df.shape

(13320, 7)

In [37]:
lower_limit = df['bhk'].quantile(0.10)
upper_limit = df['bhk'].quantile(0.90)
b = []
for x2 in df['bhk']:
    if x2 < lower_limit:
        x2 = lower_limit
        b.append(x2)
    elif x2 > upper_limit:
        x2 = upper_limit
        b.append(x2)
    else:
        b.append(x2)
        
print(b)
df['bhk'] = a

[2, 4, 3, 3, 2, 2, 4, 4, 3, 4.0, 3, 4, 2, 2, 3, 2, 3, 3, 3, 2, 2.0, 3, 4, 3, 2.0, 3, 2, 3, 2, 3, 4, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 3, 2.0, 2.0, 2, 4.0, 2, 2, 2, 2, 2, 3, 3, 2, 3, 2, 4, 2, 4.0, 2, 3, 2, 4, 2, 4.0, 2, 2, 2, 4.0, 2, 3, 2, 3, 2, 3, 2, 2, 3, 2, 4.0, 3, 4, 2, 3, 3, 4.0, 3, 2, 2, 4.0, 2, 2, 3, 4, 2, 3, 4, 3, 2, 3, 3, 2, 3, 2, 2, 2, 3, 3, 2, 2, 3, 3, 2, 3, 4, 3, 3, 3, 2, 2, 3, 3, 4, 4, 3, 2, 3, 2, 2, 4.0, 3, 3, 2, 4, 3, 2, 2, 2, 3, 3, 4.0, 4.0, 3, 2, 2, 4.0, 3, 2, 3, 4.0, 3, 2, 3, 3, 2, 2, 2, 3, 3, 4, 3, 2, 3, 4, 3, 2, 3, 3, 2, 3, 4.0, 2.0, 2, 3, 3, 3, 4.0, 2.0, 2.0, 2, 2, 3, 3, 3, 2, 3, 2, 2, 2, 2, 4, 3, 4, 4.0, 2, 2, 2, 3, 3, 2, 2, 3, 2, 2, 3, 3, 3, 2, 2, 4, 4, 3, 3, 3, 3, 2, 4.0, 2.0, 3, 3, 3, 3, 4, 2, 3, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 3, 4.0, 2, 2.0, 4.0, 2.0, 3, 2, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2, 4, 2, 2, 4.0, 3, 4, 3, 2, 2, 2, 4, 3, 3, 2, 3, 2, 3, 2, 2, 3, 3, 2, 4, 3, 3, 2, 3, 4.0, 3, 3, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 4, 3, 4, 2, 3, 3, 3, 2, 2.0, 3, 4, 3, 2, 3,

In [38]:
df.shape

(13320, 7)

In [39]:
df.describe()

total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13274.000000    1.327400e+04
mean    1445.847098      2.688814    112.565627   1445.847098    7.883254e+03
std      474.177564      1.338754    148.971674    474.177564    1.064303e+05
min      900.000000      1.000000      8.000000    900.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000   1100.000000    4.227642e+03
50%     1280.000000      2.000000     72.000000   1280.000000    5.416667e+03
75%     1690.000000      3.000000    120.000000   1690.000000    7.293505e+03
max     2427.800000     40.000000   3600.000000   2427.800000    1.200000e+07

In [40]:
df.drop(columns = ['size','price_per_sqft'],inplace = True)

In [66]:
df = df.dropna()
df = df.replace([np.inf, -np.inf], 0)

In [67]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import make_pipeline

In [68]:
df.describe()

total_sqft          bath         price           bhk
count  13274.000000  13274.000000  13274.000000  13274.000000
mean    1445.847098      2.687359    112.453654   1445.847098
std      474.177564      1.336158    149.070368    474.177564
min      900.000000      1.000000      8.000000    900.000000
25%     1100.000000      2.000000     50.000000   1100.000000
50%     1280.000000      2.000000     72.000000   1280.000000
75%     1690.000000      3.000000    120.000000   1690.000000
max     2427.800000     40.000000   3600.000000   2427.800000

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13274 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    13274 non-null  object 
 1   total_sqft  13274 non-null  float64
 2   bath        13274 non-null  float64
 3   price       13274 non-null  float64
 4   bhk         13274 non-null  float64
dtypes: float64(4), object(1)
memory usage: 622.2+ KB


In [70]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [71]:
x

array([['Electronic City Phase II', 1056.0, 2.0, 39.07],
       ['Chikka Tirupathi', 2427.800000000003, 5.0, 120.0],
       ['Uttarahalli', 1440.0, 2.0, 62.0],
       ...,
       ['Raja Rajeshwari Nagar', 1141.0, 2.0, 60.0],
       ['Padmanabhanagar', 2427.800000000003, 4.0, 488.0],
       ['Doddathoguru', 900.0, 1.0, 17.0]], dtype=object)

In [72]:
y

array([1056. , 2427.8, 1440. , ..., 1141. , 2427.8,  900. ])

In [77]:
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(sparse = False),[0])],remainder = 'passthrough')
x = ct.fit_transform(x)
x


array([[0.0, 0.0, 0.0, ..., 1056.0, 2.0, 39.07],
       [0.0, 0.0, 0.0, ..., 2427.800000000003, 5.0, 120.0],
       [0.0, 0.0, 0.0, ..., 1440.0, 2.0, 62.0],
       ...,
       [0.0, 0.0, 0.0, ..., 1141.0, 2.0, 60.0],
       [0.0, 0.0, 0.0, ..., 2427.800000000003, 4.0, 488.0],
       [0.0, 0.0, 0.0, ..., 900.0, 1.0, 17.0]], dtype=object)

In [78]:
scaler = StandardScaler(with_mean= False)
scaler.fit(x)
x = scaler.transform(x)

In [79]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [80]:
x_train

array([[0.        , 0.        , 0.        , ..., 1.89809466, 0.74844251,
        0.10062741],
       [0.        , 0.        , 0.        , ..., 5.1202158 , 2.99377005,
        2.75719104],
       [0.        , 0.        , 0.        , ..., 3.75400944, 2.24532754,
        0.59034747],
       ...,
       [0.        , 0.        , 0.        , ..., 3.07913134, 1.49688503,
        0.50313705],
       [0.        , 0.        , 0.        , ..., 2.53079288, 4.49065508,
        1.47586868],
       [0.        , 0.        , 0.        , ..., 3.1634911 , 1.49688503,
        0.43605211]])

In [81]:
y_train

array([ 900. , 2427.8, 1780. , ..., 1460. , 1200. , 1500. ])

In [82]:
x_test

array([[0.        , 0.        , 0.        , ..., 2.84714199, 2.24532754,
        0.73793434],
       [0.        , 0.        , 0.        , ..., 2.50970294, 1.49688503,
        0.42934362],
       [0.        , 0.        , 0.        , ..., 2.53079288, 2.99377005,
        1.20752892],
       ...,
       [0.        , 0.        , 0.        , ..., 2.22920673, 1.49688503,
        0.20125482],
       [0.        , 0.        , 0.        , ..., 2.49915797, 1.49688503,
        0.36896717],
       [0.        , 0.        , 0.        , ..., 3.1634911 , 4.49065508,
        0.53667952]])

In [83]:
y_test

array([1350., 1190., 1200., ..., 1057., 1185., 1500.])

In [84]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [85]:
prediction = lr.predict(x_test)
prediction

array([1350., 1190., 1200., ..., 1057., 1185., 1500.])

In [86]:
from sklearn.metrics import r2_score
r2_score(y_test,prediction)

1.0